version: '3.9'
services:

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    working_dir: /vesp

  nginx:
    image: nginx:${NGINX_VERSION}
    environment:
      - NGINX_PORT=${NGINX_PORT}
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - ./frontend:/vesp/frontend
      - ./www:/vesp/www
    ports:
      - ${NGINX_PORT}:80
      - ${NODE_ADMIN_PORT}:4000
      - ${NODE_SITE_PORT}:4100
    depends_on:
      - php-fpm
      - mariadb
    working_dir: /vesp

  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/dev.dockerfile
      args:
        - PHP_VERSION
    volumes:
      - ./core:/vesp/core
      - ./tmp:/vesp/tmp
      - ./upload:/vesp/upload
      - ./www:/vesp/www
      - ./.env:/vesp/.env
      - ./composer.json:/vesp/composer.json
      - ./composer.lock:/vesp/composer.lock
    depends_on:
      - mariadb
    environment:
      - PHP_IDE_CONFIG=serverName=VespDocker
      - COMPOSER_ALLOW_SUPERUSER=1
    working_dir: /vesp
    command: sh -c 'composer install && php-fpm'

  node:
    image: node:${NODE_VERSION}-alpine
    volumes:
      - ./frontend:/vesp/frontend
      - ./.env:/vesp/.env
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - nginx
    network_mode: 'service:nginx'
    working_dir: /vesp/frontend
    command: sh -c 'yarn && yarn dev'