version: '3.9'
services:

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./docker/mariadb:/var/lib/mysql

  nginx:
    image: nginx:${NGINX_VERSION}
    environment:
      - NGINX_PORT=${NGINX_PORT}
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - ./frontend:/vesp/frontend
      - ./www:/vesp/www
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    restart: unless-stopped
    depends_on:
      - php-fpm
      - mariadb

  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/prod.dockerfile
      args:
        - PHP_VERSION
    volumes:
      - ./core:/vesp/core
      - ./tmp:/vesp/tmp
      - ./upload:/vesp/upload
      - ./www:/vesp/www
      - ./.env:/vesp/.env
      - ./composer.json:/vesp/composer.json
      - ./composer.lock:/vesp/composer.lock
    depends_on:
      - mariadb
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    restart: unless-stopped
    working_dir: /vesp
    command: sh -c 'composer install --no-dev && composer db:migrate && crond && php-fpm'

  node:
    image: node:${NODE_VERSION}
    volumes:
      - ./frontend:/vesp/frontend
      - ./.env:/vesp/.env
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - nginx
    network_mode: 'service:nginx'
    working_dir: /vesp/frontend
    command: sh -c 'yarn && yarn generate:admin && yarn build:site && yarn start'
